apiVersion: apps/v1
kind: Deployment
metadata:
  name: siprec-devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siprec-devel
  template:
    metadata:
      labels:
        app: siprec-devel
    spec:
      imagePullSecrets:
      - name: ocir-pull-secret
      containers:
      # 1. Drachtio Server (Signaling)
      - name: drachtio-server
        image: docker.io/drachtio/drachtio-server:latest
        args: ["drachtio", "--contact", "sip:*;transport=tcp,udp", "--loglevel", "info"]
        # args: ["drachtio", "--contact", "sips:*;transport=tls", "--loglevel", "info"]
        ports:
        - containerPort: 5060
          protocol: TCP
        env:
        - name: DRACHTIO_SECRET
          value: "cymru"

      # 2. SIPREC App (The one you just built)
      - name: drachtio-srs
        image:  sin.ocir.io/ax2doumptkcp/drachtio-srs:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/config/local.json
          subPath: local.json
        env:

      # 3. Redis (State Store)
      - name: redis
        image: docker.io/redis:alpine
        ports:
        - containerPort: 6379

      volumes:
      - name: config-volume
        configMap:
          name: srs-config-devel

---
apiVersion: v1
kind: Service
metadata:
  name: siprec-devel
spec:
  selector:
    app: siprec-devel
  ports:
    - name: srs-tcp-devel
      protocol: TCP
      port: 20002
      targetPort: 5060
    - name: srs-udp-devel
      protocol: UDP
      port: 20002
      targetPort: 5060
  type: ClusterIP 
